### PR TITLE
Add eclipse-ide website and Twitter/X name

### PR DESCRIPTION
**Pull request by HannesWell**
Similar to https://github.com/eclipse-platform/.eclipsefdn/blob/main/otterdog/eclipse-platform.jsonnet, add the eclipse-ide website and Twitter/X name.
Don't add an email since there is no Mailing-List that is dedicated for the entire Eclipse-IDE/SimRel and newcomers.

### CODE REVIEW

**Review by netomi — APPROVED** [review]

**Comment by netomi** [comment]
the automerge feature is tied to the existence of a certain group that approves requests. The setup for this organization is different, but I will adjust the configuration to also support automerge feature here.

**Comment by HannesWell** [comment]
Thank you!
Applied change looks good.

**Comment by tfroment** [comment]
Thank you @netomi and @HannesWell, looks good!

**Comment by tfroment** [comment]
> Similar to https://github.com/eclipse-platform/.eclipsefdn/blob/main/otterdog/eclipse-platform.jsonnet, add the eclipse-ide website and Twitter/X name. Don't add an email since there is no Mailing-List that is dedicated for the entire Eclipse-IDE/SimRel and newcomers.

Could have added [eclipse-ide-wg@eclipse.org](mailto:eclipse-ide-wg@eclipse.org) email perhaps? WDYT @HannesWell

**Comment by HannesWell** [comment]
> > Similar to https://github.com/eclipse-platform/.eclipsefdn/blob/main/otterdog/eclipse-platform.jsonnet, add the eclipse-ide website and Twitter/X name. Don't add an email since there is no Mailing-List that is dedicated for the entire Eclipse-IDE/SimRel and newcomers.
> 
> Could have added [eclipse-ide-wg@eclipse.org](mailto:eclipse-ide-wg@eclipse.org) email perhaps? WDYT @HannesWell 

I contemplated to do that, but think that the audience targeted by this organization (i.e. developers interested in contributing to eclipse) is probably not so much interested in the WG in the first place. In the worst case we would get questions for help about the IDE on that list. 
I think we should make the documentation hosted here so good that visitors find the eclipse project they are interested in and can contact it.

**Pull request merged**
